kandinsky:
  model: kandinsky-community/kandinsky-2-2-decoder
  base_prompt: woman makeup
  dimensions: [ 512, 512 ]
  hyperparameters:
    height: 512
    width: 512
    guidance_scale: 7.5 # >1, default=7.5
    negative_prompt: ""
    strength: 0.1 # [0,1], default=50
sd15:
  model: runwayml/stable-diffusion-v1-5
  base_prompt: woman makeup
  dimensions: [ 512, 512 ]
  hyperparameters:
    guidance_scale: 7.5 # >1, default=7.5
    negative_prompt: ""
    strength: 0.5 # [0,1]
